services:
  townsquare:
    container_name: townsquare
    build:
      context: "."
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.townsquare.rule=Host(`townsquare.botc.localhost`)
      - traefik.http.routers.townsquare.entrypoints=http
      - traefik.http.services.townsquare.loadbalancer.server.port=5173
    ports:
      - 5173:5173
      - 8079:5173
      - 8078:5173
      - 8077:5173
      - 8076:5173
    develop:
      watch:
        - action: sync
          path: .
          target: /app/townsquare
          ignore:
            - node_modules/
            - dist/
            - .git/
            - .vscode/
            - server/
        - action: sync+restart
          path: vite.config.ts
          target: /app/townsquare/vite.config.ts
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json
        - action: rebuild
          path: Dockerfile
    environment:
      NODE_ENV: development
      NODE_HOSTNAME: townsquare.botc.localhost
      VITE_SERVER_URL: ws://ws.botc.localhost/
      # VITE_SERVER_URL: wss://live.clocktower.online:8080/
    working_dir: /app/townsquare
    networks:
      - proxy
    logging:
      driver: "json-file"
      options:
        max-size: "200k"

  ws_server:
    container_name: ws_server
    build:
      context: "."
      dockerfile: Dockerfile.server
    command: "node index.js"
    labels:
      - traefik.enable=true
      - traefik.http.routers.websocket.rule=Host(`ws.botc.localhost`)
      - traefik.http.routers.ws.service=ws
      - traefik.http.services.ws.loadbalancer.server.port=8081
    develop:
      watch:
        - action: sync+restart
          path: server/
          target: /app/server
          ignore:
            - server/node_modules/
        - action: rebuild
          path: Dockerfile.server
    environment:
      NODE_ENV: development
      # NODE_ALLOWED_ORIGINS: ".*"
      NODE_ALLOWED_ORIGINS: "^https?://(.*\\.?localhost)"
    ports:
      - "8081:8081"
    working_dir: /app/server
    networks:
      - proxy
    logging:
      driver: "json-file"
      options:
        max-size: "200k"

networks:
  proxy:
    name: proxy
    external: true
